# Generated by Django 5.2.5 on 2025-08-27 06:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptedmessage',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 3, 6, 58, 33, 990499, tzinfo=datetime.timezone.utc)),
        ),
    ]
