# Generated by Django 5.2.5 on 2025-08-27 07:10

import datetime
import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_encryptedmessage_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymousclient',
            name='session_id',
            field=models.CharField(default=store.models.generate_client_session_id, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='session_id',
            field=models.CharField(default=store.models.generate_cart_session_id, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='encryptedmessage',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 3, 7, 10, 50, 857256, tzinfo=datetime.timezone.utc)),
        ),
    ]
