# Generated by Django 5.2.5 on 2025-08-27 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_anonymousclient_session_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptedmessage',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 3, 7, 11, 13, 383442, tzinfo=datetime.timezone.utc)),
        ),
    ]
