# Generated by Django 5.2.5 on 2025-08-27 07:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_encryptedmessage_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptedmessage',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 3, 7, 31, 16, 465693, tzinfo=datetime.timezone.utc)),
        ),
    ]
