# Generated by Django 5.2.5 on 2025-08-27 07:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_encryptedmessage_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_per_order',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='encryptedmessage',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 3, 7, 35, 49, 930759, tzinfo=datetime.timezone.utc)),
        ),
    ]
