# Generated by Django 5.2.5 on 2025-08-27 07:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_product_max_per_order_product_stock_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptedmessage',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 3, 7, 35, 56, 797561, tzinfo=datetime.timezone.utc)),
        ),
    ]
