# Generated by Django 5.2.5 on 2025-08-27 07:44

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_encryptedmessage_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount_btc',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='amount_sats',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.anonymousclient'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_option',
            field=models.CharField(default='digital', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='ip_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='encryptedmessage',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 3, 7, 44, 39, 724792, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(blank=True, default=''),
        ),
    ]
