# Generated by Django 5.2.5 on 2025-08-27 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_order_amount_btc_order_amount_sats_order_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptedmessage',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 3, 7, 44, 46, 650459, tzinfo=datetime.timezone.utc)),
        ),
    ]
