# Generated by Django 5.2.5 on 2025-08-27 07:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_encryptedmessage_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount_btc',
        ),
        migrations.RemoveField(
            model_name='order',
            name='amount_sats',
        ),
        migrations.RemoveField(
            model_name='order',
            name='client',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_option',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ip_hash',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price_btc',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='encryptedmessage',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 3, 7, 49, 54, 71102, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(),
        ),
    ]
