# Generated by Django 5.2.5 on 2025-08-27 07:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_encryptedmessage_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount_sats',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='store.anonymousclient'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_option',
            field=models.CharField(default='digital', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='ip_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='encryptedmessage',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 3, 7, 52, 37, 824357, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
