# Generated by Django 5.2.5 on 2025-08-27 07:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_order_amount_sats_order_client_order_delivery_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptedmessage',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 3, 7, 52, 43, 745333, tzinfo=datetime.timezone.utc)),
        ),
    ]
